app_name = "goapi"
app_version = "v0.2.0"

[server]
addr = "127.0.0.1:8080"
# 单位: 秒
read_timeout = 60
write_timeout = 60
# 单位: 字节
max_header_bytes = 1048576
# 优雅停机最长等待时间，单位: 秒
shutdown_timeout = 10

[logger]
# debug/info/warn/error
level = "debug"
